[package]
name = "fov"
version = "0.1.0"
authors = ["Zachary <zacharykamerling@gmail.com>"]
edition = "2018"

[dependencies]
bencher = "*"
rand = "*"
rand_xorshift = "*"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[[bench]]
name = "fill"
harness = false